name: Python Code Style Enforcement

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Format code with Black and check for changes
        run: |
          black .
          if git diff --exit-code; then
            echo "No changes in formatting."
          else
            echo "Formatting changes detected."
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git add .
            git commit -m "Apply Black Formatting"
            git push
          fi
        shell: bash
