name: Python Code Style Enforcement

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Format code with Black
        run: black .

      - name: Check for changes
        id: diff
        run: |
          git diff --exit-code

      - name: Commit and push if changes
        if: steps.diff.outcome == 'failure'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Apply Black Formatting"
          git push
